### ISSUE TITLE
Unnecessary entry in the "files" property in package.json

### ISSUE THREAD

**Issue by Pustur** [carlosfrodrigues/react-basic-json#1]
Hi,

just wanted to let you know that you don't need to add `README.md` in the files property in `package.json`. Npm will include it by default.
Also you don't need the `.npmignore` file since you already define what gets included in `package.json`.

Reference: https://docs.npmjs.com/files/package.json#files

I can open a PR if you want.

Just a nitpick, happy coding!

**Comment by carlosfrodrigues** [comment]
Thanks for the advise :)
Please, open the PR
